---
- hosts: all
  become: True
  become_method: sudo
  tasks:

    - name: Deploy static website
      copy:
        src: ./ # We have define a html page
        dest: /opt/apache-tomcat-9.0.65/webapps/